---
#List down the packages to be installed on ec2_devops here

services:
  - apache2
#  - tomcat
  - mysql-server
  
utilities:
  - telnet
  - curl
  - dnsutils
  - openjdk-11-jdk

#List down the ports to be opened on ec2_devops
ports:
  - '80'
  - '8080'
  - '3066'
  
